#!/usr/bin/env python3
"""
Test script for all cipher explanations.
"""

import sys
sys.path.insert(0, '.')
from typing import Dict, Any, List

from cipher_toolkit import (
    caesar_encrypt, vigenere_encrypt, rail_fence_encrypt, playfair_decrypt,
    columnar_transposition_decrypt, route_cipher_decrypt,
    guess_cipher_type_brute_force, build_playfair_grid,
    derive_perm_from_key, ENGLISH_RANK
)

def explain_playfair(ciphertext: str, cand: Dict[str, Any]) -> None:
    params_str = cand["params"]
    key = ""
    if "Keyword = '" in params_str:
        key = params_str.split("Keyword = '")[1].split("'")[0]
    pt = cand["plaintext"]
    
    grid = build_playfair_grid(key)
    pos = {grid[r][c]: (r, c) for r in range(5) for c in range(5)}
    
    print("\n" + "=" * 65)
    print("          STEP-BY-STEP BREAKDOWN: PLAYFAIR CIPHER          ")
    print("=" * 65)
    print(f" Cipher Type : Playfair Cipher (5x5 Grid)")
    print(f" Keyword     : \"{key}\" (J merged into I)")
    print(f" Plaintext   : \"{pt}\"")
    print(f" Ciphertext  : \"{ciphertext}\"")
    print("-" * 65)
    print(" 5x5 Playfair Grid Matrix:")
    print("  +---+---+---+---+---+")
    for r in range(5):
        row_str = " | ".join(grid[r])
        print(f"  | {row_str} |")
    print("  +---+---+---+---+---+")
    print("-" * 65)
    print(" Digraph Transformation Breakdown (Decryption Rules):")
    print("-" * 65)
    
    clean_ct_str = "".join([c.upper() for c in ciphertext if c.isalpha()]).replace('J', 'I')
    if len(clean_ct_str) % 2 != 0:
        clean_ct_str = clean_ct_str[:-1]
        
    clean_pt_str = "".join([c.upper() for c in pt if c.isalpha()]).replace('J', 'I')
    
    digraph_idx = 1
    for i in range(0, len(clean_ct_str) - 1, 2):
        c1, c2 = clean_ct_str[i], clean_ct_str[i+1]
        p1 = clean_pt_str[i] if i < len(clean_pt_str) else '?'
        p2 = clean_pt_str[i+1] if i+1 < len(clean_pt_str) else '?'
        
        r1, col1 = pos.get(c1, (0, 0))
        r2, col2 = pos.get(c2, (0, 0))
        
        if r1 == r2:
            rule = f"Same Row {r1} (Shift Left)"
        elif col1 == col2:
            rule = f"Same Column {col1} (Shift Up)"
        else:
            rule = f"Rectangle Box Rule: ({r1},{col1}) & ({r2},{col2})"
            
        print(f"  [Digraph {digraph_idx:02d}] Plaintext '{p1}{p2}' -> Ciphertext '{c1}{c2}' | Decryption Rule: {rule}")
        digraph_idx += 1
    print("=" * 65)


def explain_columnar(ciphertext: str, cand: Dict[str, Any]) -> None:
    params_str = cand["params"]
    pt = cand["plaintext"]
    
    perm = ()
    kw_str = ""
    if "Perm = (" in params_str:
        try:
            p_part = params_str.split("Perm = (")[1].split(")")[0]
            perm = tuple(int(x.strip()) for x in p_part.split(","))
        except Exception:
            pass
    if "Keyword = '" in params_str:
        kw_str = params_str.split("Keyword = '")[1].split("'")[0]
        
    k = len(perm) if perm else 1
    n = len(pt)
    
    print("\n" + "=" * 65)
    print("     STEP-BY-STEP BREAKDOWN: COLUMNAR TRANSPOSITION        ")
    print("=" * 65)
    print(f" Cipher Type  : Columnar Transposition Cipher")
    if kw_str:
        print(f" Keyword      : \"{kw_str}\"")
    print(f" Columns (K)  : {k}")
    print(f" Read Perm    : {perm}")
    print(f" Plaintext    : \"{pt}\"")
    print(f" Ciphertext   : \"{ciphertext}\"")
    print("-" * 65)
    
    if k > 0:
        base_len = n // k
        rem = n % k
        max_rows = base_len + (1 if rem > 0 else 0)
        
        grid = []
        idx = 0
        for r in range(max_rows):
            row = []
            for c in range(k):
                if idx < n:
                    row.append(pt[idx])
                    idx += 1
                else:
                    row.append(" ")
            grid.append(row)
            
        print(" Column Grid Layout:")
        if kw_str and len(kw_str) == k:
            kw_header = "   ".join([c.upper() for c in kw_str])
            print(f"  Key Letters     :   {kw_header}")
        col_header = "   ".join([str(c) for c in range(k)])
        perm_header = "   ".join([str(p) for p in perm])
        print(f"  Column Index    :   {col_header}")
        print(f"  Read Order Rank :   {perm_header}")
        print("  " + "-" * (k * 4 + 18))
        for r_idx, row in enumerate(grid):
            r_str = "   ".join(row)
            print(f"  Row {r_idx:<2d}          :   {r_str}")
        print("-" * 65)
        print(" Transformation Explanation:")
        print("  1. Plaintext is written into the grid row-by-row from left to right.")
        print("  2. Ciphertext is generated by reading columns in order of Read Order Rank.")
        print("  3. Decryption re-assembles the columns into grid and reads row-by-row.")
    print("=" * 65)


def explain_route(ciphertext: str, cand: Dict[str, Any]) -> None:
    params_str = cand["params"]
    pt = cand["plaintext"]
    
    rows, cols = 0, 0
    pattern = "Standard"
    if "Grid = " in params_str:
        try:
            dim_str = params_str.split("Grid = ")[1].split(",")[0]
            rows, cols = map(int, dim_str.split("x"))
        except Exception:
            pass
    if "Pattern = " in params_str:
        pattern = params_str.split("Pattern = ")[1].split("(")[0].strip()
        if " (trailing" in params_str:
            pattern = params_str.split("Pattern = ")[1].split(" (trailing")[0].strip()
            
    print("\n" + "=" * 65)
    print("            STEP-BY-STEP BREAKDOWN: ROUTE CIPHER           ")
    print("=" * 65)
    print(f" Cipher Type : Route Cipher")
    print(f" Grid Size   : {rows} Rows x {cols} Cols")
    print(f" Pattern     : {pattern}")
    print(f" Plaintext   : \"{pt}\"")
    print(f" Ciphertext  : \"{ciphertext}\"")
    print("-" * 65)
    
    if rows * cols == len(ciphertext) or rows * cols == len(pt):
        n = len(ciphertext)
        grid = [['' for _ in range(cols)] for _ in range(rows)]
        
        if "Column-by-Column (Top-Down)" in params_str:
            idx = 0
            for c in range(cols):
                for r in range(rows):
                    if idx < n:
                        grid[r][c] = ciphertext[idx]
                        idx += 1
        elif "Column-by-Column (Bottom-Up)" in params_str:
            idx = 0
            for c in range(cols):
                for r in range(rows - 1, -1, -1):
                    if idx < n:
                        grid[r][c] = ciphertext[idx]
                        idx += 1
        elif "Boustrophedon (Zigzag)" in params_str:
            idx = 0
            for r in range(rows):
                if r % 2 == 0:
                    for c in range(cols):
                        if idx < n:
                            grid[r][c] = ciphertext[idx]
                            idx += 1
                else:
                    for c in range(cols - 1, -1, -1):
                        if idx < n:
                            grid[r][c] = ciphertext[idx]
                            idx += 1
        else:
            idx = 0
            for r in range(rows):
                for c in range(cols):
                    if idx < n:
                        grid[r][c] = ciphertext[idx]
                        idx += 1
                        
        print(f" Route Grid Layout ({rows} Rows x {cols} Cols):")
        top_b = "  +" + "---+" * cols
        print(top_b)
        for r in range(rows):
            r_str = " | ".join(grid[r][c] if grid[r][c] else ' ' for c in range(cols))
            print(f"  | {r_str} |")
        print(top_b)
        print("-" * 65)
        print(" Transformation Explanation:")
        print(f"  1. Ciphertext is loaded into grid according to pattern: {pattern}")
        print("  2. Reading grid row-by-row reconstructs the Plaintext.")
    print("=" * 65)


def explain_statistical_fallback(ciphertext: str, fb: Dict[str, Any]) -> None:
    print("\n" + "=" * 65)
    print("  STEP-BY-STEP BREAKDOWN: STATISTICAL CRYPTANALYSIS FALLBACK   ")
    print("=" * 65)
    print(f" Analysis Result : Statistical Fallback (No Dictionary Matches)")
    print(f" Guessed Cipher  : {fb.get('guess', 'Unknown')}")
    print(f" Confidence      : {fb.get('confidence', 'Low')}")
    print("-" * 65)
    print(" Reasoning & Deductions:")
    print(f"  {fb.get('reasoning', 'N/A')}")
    print("-" * 65)
    details = fb.get("details", {})
    if details:
        print(" Statistical Metrics Breakdown:")
        print(f"  - Total Alphabetic Letters : {details.get('total_letters', 'N/A')}")
        print(f"  - Index of Coincidence (IC): {details.get('index_of_coincidence', 'N/A')}")
        print(f"    (Reference: Standard English IC ~0.0667, Random Text IC ~0.0385)")
        top_lets = details.get("top_letters", [])
        if top_lets:
            top_str = ", ".join(f"'{char}': {cnt}" for char, cnt in top_lets)
            print(f"  - Top Ciphertext Frequencies: {top_str}")
        if "best_caesar_shift" in details:
            print(f"  - Best Candidate Caesar Shift: {details.get('best_caesar_shift')}")
    print("=" * 65)

def test_remaining():
    cand_pf = {"cipher": "Playfair Cipher", "params": "Keyword = 'LEMON'", "plaintext": "MEETMEATMIDNIGHT", "score": 1.0}
    explain_playfair("LXFOPVEFRNHR", cand_pf)

    cand_col = {"cipher": "Columnar Transposition", "params": "Keyword = 'ZEBRA', Perm = (4, 1, 0, 3, 2)", "plaintext": "MEETMEATMIDNIGHT", "score": 1.0}
    explain_columnar("EATMMMIDNEETTX", cand_col)

    cand_rt = {"cipher": "Route Cipher", "params": "Grid = 4x4, Pattern = Column-by-Column (Top-Down)", "plaintext": "MEETMEATMIDNIGHT", "score": 1.0}
    explain_route("MMAMEEAITETDNGHT", cand_rt)

    fb_report = {
        "guess": "Transposition (Statistical Fallback)",
        "confidence": "Medium (Statistical)",
        "reasoning": "Unshifted letter frequencies match standard English.",
        "details": {"total_letters": 16, "index_of_coincidence": "0.0667", "top_letters": [('E', 4), ('T', 3), ('M', 3)], "best_caesar_shift": 0}
    }
    explain_statistical_fallback("MMAMEEAITETDNGHT", fb_report)

if __name__ == "__main__":
    test_remaining()
